name: Publish go package

#env:
#  CI: false

on:
  push:
    tags:
      # supports: v1.2.3 and v1.2.3.alpha.1, v1.2.3-beta.3
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.18'
      - name: Verify Go
        run: go version
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Fetch latest tag
        id: latestTag
        run: echo "latest_tag=$(echo git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Publish to pkg.go.dev
        run: GOPROXY=proxy.golang.org go list -m github.com/apudiu/event-scheduler@${{steps.latestTag.outputs.latest_tag}}
      - name: Success msg
        run: echo 'Published package version - ${{steps.latestTag.outputs.latest_tag}}. Url - https://pkg.go.dev/github.com/apudiu/event-scheduler'
